project_name: stree
version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: false

builds:
  - id: stree
    binary: stree
    main: .
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -buildid=
      - -X sigs.k8s.io/release-utils/version.gitVersion={{ .Version }}
      - -X sigs.k8s.io/release-utils/version.gitCommit={{ .FullCommit }}
      - -X sigs.k8s.io/release-utils/version.gitTreeState={{ if .IsGitDirty }}dirty{{ else }}clean{{ end }}
      - -X sigs.k8s.io/release-utils/version.buildDate={{ .CommitDate }}
    env:
      - CGO_ENABLED=0

signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  signature: "${artifact}.sigstore.json"
  args:
    - "sign-blob"
    - "--bundle=${signature}"
    - "${artifact}"
    - "--yes"
  artifacts: archive
  output: true

nfpms:
  - id: stree
    package_name: stree
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: viveksahu26
    homepage: https://github.com/viveksahu26/
    maintainer: Vivek Sahu Authors vivekkumarsahu650@gmail.com
    description: For a provided SBOM, it helps vizualize the relationships between the components and their dependencies in a directory Tree or file Tree structure like tree command does for linux.
    license: "Apache License 2.0"
    formats:
      - apk
      - deb
      - rpm


archives:
  - id: stree
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

snapshot:
  version_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: auto
  draft: true
  make_latest: true 
