project_name: stree
version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - /bin/bash -c 'if [ -n "$(git --no-pager diff --exit-code go.mod go.sum)" ]; then exit 1; fi'

gomod:
  proxy: true

builds:
  - id: binaries
    binary: stree-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    main: .
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "{{ .Env.LDFLAGS }}"
    env:
      - CGO_ENABLED=0

nfpms:
  - id: stree
    package_name: stree
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: viveksahu26
    homepage: https://github.com/viveksahu26/
    maintainer: Vivek Sahu Authors vivekkumarsahu650@gmail.com
    builds:
      - binaries
    description: For a provided SBOM, it helps vizualize the relationships between the components and their dependencies in a directory Tree or file Tree structure like tree command does for linux.
    license: "Apache License 2.0"
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: /usr/bin/stree-{{ .Os }}-{{ .Arch }}
        dst: /usr/bin/stree
        type: "symlink"

archives:
- format: binary
  name_template: "{{ .Binary }}"
  allow_different_binary_count: true

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow
  draft: true

sboms:
  -
    artifacts: binary
    documents:
      - "${artifact}.spdx.sbom"
